# permissions for end users to view responders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: responder-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-2-controller
    app.kubernetes.io/part-of: test-2-controller
    app.kubernetes.io/managed-by: kustomize
  name: responder-viewer-role
rules:
- apiGroups:
  - delivery.controller-e2e-framework
  resources:
  - responders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.controller-e2e-framework
  resources:
  - responders/status
  verbs:
  - get
