---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: test-2-controller-manager-role
rules:
- apiGroups:
  - delivery.controller-e2e-framework
  resources:
  - responders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.controller-e2e-framework
  resources:
  - responders/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.controller-e2e-framework
  resources:
  - responders/status
  verbs:
  - get
  - patch
  - update
