apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: test-2-controller
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-2-controller
    app.kubernetes.io/part-of: test-2-controller
    app.kubernetes.io/managed-by: kustomize
  name: test-2-controller
  namespace: system
